name: testing
on:
  push:
    branches:
      - testing
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: install dependencies and build
        run: npm install && npm run build

      - name: run cypress tests in chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"
